### ISSUE TITLE
issues in custom ai

### ISSUE THREAD

**Issue by piuz** [CoCoPIE-Group/XGen-Report#10]
When I use custom ai, I see the following problem.
[2022-09-17-04-12-44-log.txt](https://github.com/CoCoPIE-Group/XGen-Report/files/9587089/2022-09-17-04-12-44-log.txt)
It seems to ask for Key: 'global_sparsity', which is not available. 

The setting is attached.
![1122](https://user-images.githubusercontent.com/75514414/190727115-e0020254-b0bb-4616-88e0-436b1b7bc654.jpg)
I tried other settings such as compatibility test and pruning, the problem still happens. 

Here is my original train script and xgen.json.
[scripts.zip](https://github.com/CoCoPIE-Group/XGen-Report/files/9587108/scripts.zip)

**Comment by uniyushu** [comment]
It looks like some code is missing in your code. You need to add xgen_record outside the for loop. The train script will work fine.
<img width="934" alt="image" src="https://user-images.githubusercontent.com/20262193/191257079-fa2cd8b3-ea33-4065-b4c5-9bdc5cf3062b.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/20262193/191257145-70e620f8-ceb3-474d-86d1-e6fed94517df.png">

**Comment by piuz** [comment]
Thanks. I solved this problem with the advice. But it worked with an old version of XGen. 

Now I upgrade xgen to the newest version. A new problem shows up. 
[xgen_mnist.zip](https://github.com/CoCoPIE-Group/XGen-Report/files/9693404/xgen_mnist.zip)
I attached my source files with train script, pretrained model and xgen.json. 

For the customai with MNIST, I can not run compatibility test, pruning or scaling. I attached the log files. 

[20221002194936.zip](https://github.com/CoCoPIE-Group/XGen-Report/files/9693424/20221002194936.zip)
[20221002195732.zip](https://github.com/CoCoPIE-Group/XGen-Report/files/9693425/20221002195732.zip)
