### ISSUE TITLE
path issues in custom ai

### ISSUE THREAD

**Issue by piuz** [CoCoPIE-Group/XGen-Report#11]
In custom ai, we need to input the path of the train script and the xgen.json. 
![1122](https://user-images.githubusercontent.com/75514414/190728358-f94fae5e-38a0-4f32-98f7-77d3f620ba9f.jpg)
But the xgen.json path must point to the file, while the training script must point to the directory of the script. These two paths are inconsistent, one for a file and the other one for a directory. I can figure it out quickly. I just feel it better if the meanings of paths can be consistent. 

Besides, for custom ai, users need to provide a xgen.json file. The manual does not  mention this in the custom ai part. Users do not know how to prepare this configuration file. I can use a configuration file from another common ai project. But as we do not have instructions about this, I am not sure whether the configuration file is correct.

**Comment by xinzhang-cocopie** [comment]
Thanks for your advice, it will be fixed in next release.
