### ISSUE TITLE
check onnx file in custom ai

### ISSUE THREAD

**Issue by piuz** [CoCoPIE-Group/XGen-Report#12]
In the manual, the 'run the check' step has some problems. If we run the following command, it will has some problems. 
```
/usr/local/compiler/cocogen/xgen_check.py [the onnx file]
```
But if we run the following, it will work. 
```
python  /usr/local/compiler/cocogen/xgen_check.py  [the onnx file]
```

**Comment by xinzhang-cocopie** [comment]
Thanks for your feedback.
It was a mistake in the doc,  we will fix it asap.
