### ISSUE TITLE
can not find custom dataset for mobilenet imagenet of common ai

### ISSUE THREAD

**Issue by piuz** [CoCoPIE-Group/XGen-Report#13]
When testing MobileNet-ImageNet with custom dataset, it could not find the custom dataset. The log file is attached. 

[error_mobilenet.txt](https://github.com/CoCoPIE-Group/XGen-Report/files/9590454/error_mobilenet.txt)

We can use the same custom dataset for other projects like ResNet-ImageNet.

**Comment by xipengshen** [comment]
@kaixu-cocopie

**Comment by xipengshen** [comment]
@kaixu-cocopie Please check with Guanhua about this issue. It requires some changes to the common AI models.

**Comment by xipengshen** [comment]
@piuz Can you try the new version of XGen on this and report your observations?

**Comment by xipengshen** [comment]
@gdingcoco please follow up.

**Comment by gdingcoco** [comment]
Datasets for mobilenet should have the same structure as imagenet, which means you have to make sure, you have a "train" and "val" folder, and each folder should have several sub-folder for each class.

**Comment by piuz** [comment]
Thanks. We can use the custom datasets now with new version and correct path.
