### ISSUE TITLE
Issues during Compatibility Test within XGen

### ISSUE THREAD

**Issue by aayooush** [CoCoPIE-Group/XGen-Report#14]
I am trying to optimize a basic MNIST model, with scripts linked below.

The example is taken from [MNIST](https://github.com/pytorch/examples/tree/32f0c1e1073913e75fa75b848bccdbf011b2a569/mnist).

After running `run_xgen`, I get in the XGen container, and I am able to run the model, and also create the ONNX model.
On running the Compatibility check,
```
python /usr/local/compiler/cocogen/xgen_check.py [the onnx file]
```
 I get 
```
INFO: Check passed.
```

While trying to achieve the same from within XGen conda env, by running `XGen`, I get the following error:

```
Traceback (most recent call last):
  File "xgen_scripts.py", line 96, in main
    xgen(training_main, run_mock, training_script_path=training_script_path, log_path=log_path)
  File "/root/miniconda3/envs/xgen/lib/python3.7/site-packages/xgen_main-1.0.11-py3.7.egg/xgen/xgen_run.py", line 402, in xgen
    internal_data = train_module(job, training_main)
  File "/root/miniconda3/envs/xgen/lib/python3.7/site-packages/xgen_main-1.0.11-py3.7.egg/xgen/train_module.py", line 160, in train_module
    args_ai = model_train_main(job, training_main)
  File "/root/miniconda3/envs/xgen/lib/python3.7/site-packages/xgen_main-1.0.11-py3.7.egg/xgen/train_module.py", line 145, in model_train_main
    raise Exception('Training failed')
Exception: Training failed
```

Complete Log File: [Log](https://github.com/aayooush/temp/blob/main/XGen_Log-Sep16.txt)
Train_script_main: [Train_Script](https://github.com/aayooush/temp/blob/main/train_script_main.py)
Config: [Config](https://github.com/aayooush/temp/blob/main/xgen.json)

**Comment by uniyushu** [comment]
You need add missing entry point if __name__ == '__main__', we also provide [test_nd.py](https://github.com/CoCoPIE-Group/XGen-Report/blob/main/test_nd.py) to test your code.
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/20262193/191261901-c94e8b45-322e-4219-9e35-10f21bc6e499.png">
<img width="919" alt="image" src="https://user-images.githubusercontent.com/20262193/191261977-8c219e54-32ab-4c0c-9080-64ec40e3e1ae.png">
