### ISSUE TITLE
XGen folder is not created after install command 

### ISSUE THREAD

**Issue by jakariamd** [CoCoPIE-Group/XGen-Report#16]
All previous steps worked well, except the bash xgen_docker_deploy.sh --install command. 
Output from running this command: Tools checking passed.
But no XGen folder is created under the home directory.

**Comment by xinzhang-cocopie** [comment]
thanks for you feedback.
We will try  to reproduce this issue.

**Comment by xipengshen** [comment]
@xinzhang-cocopie Any update?

**Comment by xinzhang-cocopie** [comment]
> 

Can't reproduce it, maybe the user didn't  in docker group?  we will add this detection in the script anyway.

**Comment by xipengshen** [comment]
@jakariamd Can you install the latest version (http://xgen-install.cocopie.ai/xgen_docker_deploy.sh) and try again?
