### ISSUE TITLE
can not load pretrained weights for s2-1d with the default setting

### ISSUE THREAD

**Issue by piuz** [CoCoPIE-Group/XGen-Report#18]
[2022-09-24-07-46-08-log.txt](https://github.com/CoCoPIE-Group/XGen-Report/files/9637532/2022-09-24-07-46-08-log.txt)

When I run the compatibility test for video classification with R2+1d on the default UCF101 dataset, I got the error that 'can not load pretrained weights for s2-1d'. I attached the log file.

I run the compatibility test on the default dataset. I just make choice and do not need to provide any data or model. But I still get this error.

**Comment by xinzhang-cocopie** [comment]
@piuz thanks for your feedback.

Did you have  `git-lfs` in your env?  s2-1d has a large pertained file in project, managed using git-lfs.
if  `git-lfs` installed,  `git pull` or `git clone`  will automatically handle large file. otherwise  the file content is a hash string.

please check  `du -sh  video-classification-s2-1d/pre_trained_model/r2+1d_ucf101_dense_top1-94.0_unpruned.pt`.

**Comment by piuz** [comment]
I do not have git-lfs since the manual does not mention these packages for the environment. I run 
```
du -sh video-classification-s2-1d/pre_trained_model/r2+1d_ucf101_dense_top1-94.0_unpruned.pt
``` 
it shows that
```
4.0K  video-classification-s2-1d/pre_trained_model/r2+1d_ucf101_dense_top1-94.0_unpruned.pt
```

**Comment by xinzhang-cocopie** [comment]
Normally, the file size should be 124M, you can follow bottom line to install,

` curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash`
` sudo apt-get install git-lfs`
` git lfs install`

this section is not easy to attention, it is refer to [docs_installation_step1](http://xgen.cocopie.ai/2_Installation/#step-1-install-nvidia-driver-docker-and-nvidia-container-toolkit-on-your-host), anyway we will add more detection in `XGen`.

**Comment by xinzhang-cocopie** [comment]
what's your XGen version? maybe your `XGen` version is behind, please upgrade to the latest.

**Comment by piuz** [comment]
Do you have the latest xgen_docker_deploy.sh file? Maybe you can send me through email. I do not find a link to download this file. And my current version does not support auto upgrade.

**Comment by piuz** [comment]
never mind. I got the upgrade file.
