### ISSUE TITLE
Downloaded model cannot be detected by XGen immediately

### ISSUE THREAD

**Issue by 2015xli** [CoCoPIE-Group/XGen-Report#2]
In XGen interactive mode, if the selected model is not present, it asks the user to download the model. After I have downloaded the model, and relaunch XGen interactive mode, XGen still quits and asks to download the model if I select the same model. 

If it is due to docker's problem (i.e., that we cannot fix), it is better to give a notice to the user about the potential issue so that the user won't be confused.

Btw, I didn't exit the container throughout the process, since the notice looks to assume the user should download within the container. It is better to give an explicit notice whether the user should exit the container or not. (Otherwise the interactive mode operations and the container shell operations are confusing to people who are not familiar with container.)

**Comment by Lovemma** [comment]
In release version v1.0.13, we support the download common AI model automatically.
