### ISSUE TITLE
Connectivity issue during XGen installation.

### ISSUE THREAD

**Issue by EthanGuan** [CoCoPIE-Group/XGen-Report#3]
## Executing command: 
`bash xgen_docker_deploy.sh --install --region HK`

## Issues:
1. The bash script to install XGen **may or may not** report errors due to connectivity issues. I.e., The script quit without error messages even though the installation procedure is not finished.
2. It takes at least hours to download the XGen docker image from China's mainland.

**Comment by Ucag** [comment]
This is the issue of client network, after test, your client network is only top to 4mb/s and on average is 1mb/s. This is caused by the slow network of Beijing Super Cloud Network Center.
