### ISSUE TITLE
Occasionally, XGen does not quit after a task has been executed

### ISSUE THREAD

**Issue by huzq85** [CoCoPIE-Group/XGen-Report#6]
## Issues
XGen does not quit after a task has been executed.

## Environment
1. Do not connect phones to the host.
2. Multiple users use the same docker container.

## Reproduce Steps
1. User1 uses XGen to execute some tasks.
2. Wait for a long time until the tasks have been finished (Use "top" to check the resource utilization, XGen is still there but no Python subprocesses).
![XGen_does_not_exit](https://user-images.githubusercontent.com/3875962/190671816-cefb90d0-3874-4d40-9712-b4fe74d0e765.png)
4. User2 login to the same docker container to run XGen.

## Results
"Another active XGen instance is found. This XGen is a single-instance version. Please wait for it to complete."

## Expectations
1. XGen quits correctly after tasks are finished.

**Comment by Lovemma** [comment]
In our environment, we do not reproduce this problem, can I connect to your environment to reproduce this problem?

**Comment by huzq85** [comment]
> 
This issue does not occur every time when users finish their tasks with XGen. I have encountered this issue twice during the testing. We could sync offline for my testing environment, do you think it is OK?

**Comment by Lovemma** [comment]
ok, how do we do sync offline?

**Comment by hustc12** [comment]
> ok, how do we do sync offline?

I sent an email (to dependence.letgo@gmail.com) and replied with my contact information.
