### ISSUE TITLE
Negative values would confuse users

### ISSUE THREAD

**Issue by huzq85** [CoCoPIE-Group/XGen-Report#7]
## Issues
After performing some tasks, negative "Quality Score" and "Latency" values would confuse users.

## Environment
1. Do not connect phones to the host.

## Reproduce Steps
1. Run XGen, then select UNet, Pruning
2. Select latency, input desired latency 200ms
3. Input quality score >= 90
4. Input batch size per GPU: 8

## Results
![negative_results](https://user-images.githubusercontent.com/3875962/190629546-e440782d-42b8-4269-9b0e-69b7a285b405.png)

## Expectations
Users may expect some explanations for these negative values.

**Comment by xipengshen** [comment]
@kaixu-cocopie The Quality Score of Unet was assumed to be IoU. It is strange that the value could be negative. What is the actual meaning of the quality score of Unet?
