### ISSUE TITLE
XGen does not check some of the invalid inputs before executing

### ISSUE THREAD

**Issue by huzq85** [CoCoPIE-Group/XGen-Report#8]
## Issues
XGen does not validate some of the inputs before executing.

## Environment
1. Do not connect phones to the host.

## Reproduce Steps
1. Type in the configurations shown in the following snapshot.
![invalid_input](https://user-images.githubusercontent.com/3875962/190647158-b93e4a02-cd0e-4c26-98ed-e77d63e39aa4.PNG)
![invalid_input2](https://user-images.githubusercontent.com/3875962/190647180-6d598cb2-0869-443a-a71f-26447fc0a3c0.PNG)

## Results
XGen still can do execution.

## Expectations
1. The desired latency should not be negative values.
2. In the 2nd snapshot, "10m" is valid for XGen but the unit "m" is not shown in examples.

**Comment by Lovemma** [comment]
We will fix the negative value in release version v1.0.14,  and m is brief instruction which means min.
